export const FEATURES = {
  AUTH: true,
  PROFILE: true,
  SINGLE_CHAT: true,
  GROUP_CHAT: true,
  TEXT_MESSAGE: true,
  IMAGE_MESSAGE: true,
  FILE_MESSAGE: true,
  VOICE_CALL: true,
  VIDEO_CALL: true,
  CONTACTS: true,
  FRIEND_REQUESTS: true,
  USER_SEARCH: true,
  BLOCK_USER: true,
  REPORT: true,
  SENSITIVE_WORDS: true,
  HELP_CENTER: true,
  PRIVACY_SETTINGS: true,
  DELETE_ACCOUNT: true,
  ADMIN_DASHBOARD: true,
} as const;
